### ISSUE TITLE
Does not work on Apple Silicon

### ISSUE THREAD

**Issue by GoanSausage** [relikd/Memmon#2]
The app runs using Rosetta but does not remember window positions when an external display is plugged in. Accessibility privileges have been granted. 

It _is_ moving windows because they are all half off my M1 Air's internal display when I plug in an external display but do not move to it. They stay that way once the external display is unplugged.

Could I request a Universal Binary, please? For those of us on Apple Silicon hardware, who don't have the skills to compile this for ourselves.

Thank you for this utility. Just wish it worked for me.

**Comment by relikd** [comment]
hmm, I do not know why it does not move your windows to the new display. It should. Can you give the contex? macOS 11 oder 12? Is it all windows / apps or just a few? Did you close Memmon in between (though then they wouldn't be moved at all)? ... very strange.

as to the universal binary: I do compile this app at home where I don't have access to an M1. I can try and compile one at work, but I can't test if it will indeed be universal. I'll just send it to you later. (and btw. you don't need skills you just need swift installed (comes with Xcode) ;) then you can run `swift src/main.swift`)

**Comment by ubapsi** [comment]
You can try this universal build: [Memmon_v1.4.tar.gz](https://github.com/relikd/Memmon/files/7569104/Memmon_v1.4.tar.gz). If that does not work you can try version 1.2 without spaces support, maybe it is a concurrency issue.

**Comment by GoanSausage** [comment]
> You can try this universal build: [Memmon_v1.4b.tar.gz](https://github.com/relikd/Memmon/files/7569308/Memmon_v1.4b.tar.gz). If that does not work you can try version 1.2 without spaces support, maybe it is a concurrency issue.

Thank you so much. This works perfectly (except it wants me to give it accessibility access on every launch.)

**Comment by GoanSausage** [comment]
> hmm, I do not know why it does not move your windows to the new display. It should. Can you give the contex? macOS 11 oder 12? Is it all windows / apps or just a few? Did you close Memmon in between (though then they wouldn't be moved at all)? ... very strange.
> 
> as to the universal binary: I do compile this app at home where I don't have access to an M1. I can try and compile one at work, but I can't test if it will indeed be universal. I'll just send it to you later. (and btw. you don't need skills you just need swift installed (comes with Xcode) ;) then you can run `swift src/main.swift`)

Hi, Sorry for not providing more context. This is on the latest release of MacOS Monterey on an M1 Air. The universal binary provided by ubapsi above, works perfectly.

Only other issue is that the app requests accessibility permission upon every launch, even though it has already been granted.

**Comment by ubapsi** [comment]
if it does that, then the accessibility isn't working properly. Have you tried to delete the old app? The two will interfere because they have the same bundle identifier. I'll try to build a signed universal version later which can then replace the original. Accessibility permissions are linked once they are signed.

**Comment by GoanSausage** [comment]
Deleted the older app. Emptied the bin. Removed it's entry from permissions, logged out and back in. With the universal binary added to my login items, I get the permissions pop-up upon each login.

**Comment by ubapsi** [comment]
You can right-click on the app "show package contents" and edit the `Contents/Info.plist` just change the `1.4b` to `1.4c` maybe that will do the trick. I've strugled with it too in the last 5 minutes to get it updated. Or just wait for the next update.

As for the hide status icon, yes thats intended behavior (see readme). The "hide icon" is per run, if you want it permanently you have to run `defaults write de.relikd.Memmon icon -int 0` in Terminal.

**Comment by GoanSausage** [comment]
> You can right-click on the app "show package contents" and edit the `Contents/Info.plist` just change the `1.4b` to `1.4c` maybe that will do the trick. I've strugled with it too in the last 5 minutes to get it updated. Or just wait for the next update.
> 
> As for the hide status icon, yes thats intended behavior. The "hide icon" is per run, if you want it permanently you have to run `defaults write de.relikd.Memmon icon -int 0` in Terminal.

Thank you so much, you've solved both the issues. 

I read the instructions about hiding the icon on the main page but thought there was now a GUI option. 

I need to learn to read good.
