### ISSUE TITLE
Hammerspoon?

### ISSUE THREAD

**Issue by hmijail** [relikd/Memmon#7]
Just a clarification request: why the mention of Hammerspoon in the Readme, did you mean that there is an (already existing) way to do what Memmon does with Hammerspoon? Or just that one could implement something in there?
(I tried searching for something ready-made but couldn't find anything)

**Comment by relikd** [comment]
Ah, I see. I found [this post](https://apple.stackexchange.com/a/140352) which provides an example for [Slate](https://github.com/jigish/slate) but a comment below mentioned  that Slate isn't maintained anymore and suggested Hammerspoon instead. I didn't try Hammerspoon so I can't tell how difficult such a script would be. Feel free to clarify the Readme if you'd like.
